### ISSUE TITLE
Require e-mail sign-in for guests?

### ISSUE THREAD

**Issue by joepio** [Swetrix/swetrix-api#200]
Hi there! (sorry if this is the wrong repo!)

I'm using swetrix to give one of my customers access to their dashboard using the password feature. I shared a password for this dashboard some time ago, but since a while there's a registration / sign-in requirement. So I instructed my customer to sign up, and now they have a 14-day trial, which led them to send me an email about whether they will lose access in two weeks.

I'm not quite sure whether the UX has changed (e.g. show sign-in screen when the password screen should be shown) or if I'm misremembering things.

Cheers!

**Comment by Blaumaus** [comment]
Hi @joepio, your customer does not have to buy a paid subscription to access data on shared projects. This should have been and will be clarified by us later on the billing page.

Regarding the redirection of password protected projects - people you share your project link with don't need an account to view it (whether it's a public project or a password protected one).

I have just tested this myself on a password protected project, and there seems to be a problem with it sometimes redirecting to a login page (probably since we added funnels). This is a bug and will be fixed soon.
Sorry for the inconvenience.

**Comment by Blaumaus** [comment]
I'll leave a message in this thread when this issue will be fixed

**Comment by Blaumaus** [comment]
@joepio this bug was indeed an oversight after I added funnels.
The fix is located at https://github.com/Swetrix/swetrix-fe/commit/b7efdf2d1cff69865733e16629ec8902b293cb5e and is being deployed for now.
It should be working well for you now

**Comment by joepio** [comment]
Thank you for the quick response and fix!
